version: '3'

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql_wb
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: "hyeeyoung"
      MYSQL_PASSWORD: "wishboard"
      MYSQL_DATABASE: "wishboard"
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis:alpine
    container_name: redis_wb
    command: redis-server --port 6379
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
