# This is a basic workflow to help you get started with Actions

name: deploy-dev

on:
  # push 시 자동 트리거
  push:
    branches: [ develop ]
  # 직접 트리거
  workflow_dispatch:
    inputs:
      branch:
        description: '배포할 브랜치'
        required: true
        default: 'develop'

env:
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME_DEV }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: create secret files
        working-directory: ./src/main/resources
        run: |
          touch application.yml
          touch application-dev.yml
          echo "${{ secrets.APPLICATION_YML }}" >> application.yml
          echo "${{ secrets.APPLICATION_DEV_YML }}" >> application-dev.yml

      #          mkdir firebase
      #          touch ./firebase/firebase_service_key.json
      #          echo "${{ secrets.FIREBASE_SERVICE_KEY_JSON }}" >> ./firebase/firebase_service_key.json
      #          sed -i 's/#/"/g' ./firebase/firebase_service_key.json

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      #      - name: Test with Gradle
      #          run: ./gradlew test

      - name: Build with Gradle without test
        run: ./gradlew build -x test
        shell: bash

      - name: Make zip file
        run: zip -r ./wishboard-v2-build-dev.zip .
        shell: bash

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER_NAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "wishboard-v2-build-dev.zip"
          target: "/home/wishboard-v2/dev/current"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # ssh에 접속하여 script 실행
    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER_NAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/wishboard-v2/dev/current
            unzip -o wishboard-v2-build-dev.zip
            chmod +x ./deploy-server.sh
            sh ./deploy-server.sh
