# This is a basic workflow to help you get started with Actions

name: deploy-dev

on:
  # push 시 자동 트리거
  push:
    branches: [ develop ]
  # 직접 트리거
  workflow_dispatch:
    inputs:
      branch:
        description: '배포할 브랜치'
        required: true
        default: 'develop'

env:
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME_DEV }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: create secret files
        working-directory: ./src/main/resources
        run: |
          touch application.yml
          touch application-dev.yml
          echo "${{ secrets.APPLICATION_YML }}" >> application.yml
          echo "${{ secrets.APPLICATION_DEV_YML }}" >> application-dev.yml

      #          mkdir firebase
      #          touch ./firebase/firebase_service_key.json
      #          echo "${{ secrets.FIREBASE_SERVICE_KEY_JSON }}" >> ./firebase/firebase_service_key.json
      #          sed -i 's/#/"/g' ./firebase/firebase_service_key.json

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      #      - name: Test with Gradle
      #          run: ./gradlew test

      - name: Build with Gradle without test
        run: ./gradlew build -x test
        shell: bash

      - name: Make zip file
        run: mkdir -p wishboard-v2-build-dev
        shell: bash

      - name: Copy build files
        run: |
          cp -r ./build/libs/* ./wishboard-v2-build-dev/ 
          cp -r ./v2-pm2-run-config.js ./wishboard-v2-build-dev/ 
          cp -r ./deploy.sh ./wishboard-v2-build-dev/
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY_DEV }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            wishboard-v2-build-dev s3://$AWS_S3_BUCKET_NAME/wishboard-v2-build-dev
