# This is a basic workflow to help you get started with Actions

name: deploy-prod

on:
  # push 시 자동 트리거
  push:
    branches: [ main ]
  # 직접 트리거
  workflow_dispatch:
    inputs:
      branch:
        description: '배포할 브랜치'
        required: true
        default: 'main'

env:
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME_PROD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: create secret files
        working-directory: ./src/main/resources
        run: |
          touch application.yml
          touch application-dev.yml
          echo "${{ secrets.APPLICATION_YML }}" >> application.yml
          echo "${{ secrets.APPLICATION_DEV_YML }}" >> application-dev.yml

      #          mkdir firebase
      #          touch ./firebase/firebase_service_key.json
      #          echo "${{ secrets.FIREBASE_SERVICE_KEY_JSON }}" >> ./firebase/firebase_service_key.json
      #          sed -i 's/#/"/g' ./firebase/firebase_service_key.json

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle without test
        shell: bash

      - name: Make zip file
        run: zip -r ./wishboard-dev-build.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY_DEV }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./wishboard-dev-build.zip s3://$AWS_S3_BUCKET_NAME/wishboard-v2-build.zip
